# Generated by Django 4.2.7 on 2023-11-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_booking_alter_bookingtable_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='bookingDate',
            field=models.DateTimeField(),
        ),
    ]
