# Generated by Django 4.2.7 on 2023-11-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_delete_booking_alter_bookingtable_bookingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='bookingDate',
            new_name='reservation_date',
        ),
    ]
